application: cuspaceflight-snippets
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /register
  script: register.py
  login: required

- url: /dev_console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /admin/.*
  script: admin.py
  login: required

- url: /email/.*
  script: email.py
  login: admin

- url: /.*
  script: snippets.py
  login: required

